version: '3'
services:
  app:
    build: .
    command: yarn start
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABABSE: gamification
    ports:
      - 5433:5433
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
